globals = {'LibStub', 'GetBuildInfo', 'UIDROPDOWNMENU_MAXLEVELS', 'UIDROPDOWNMENU_MAXBUTTONS', 'UIDD_REFRESH_OVERREAD_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_MENU', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'FACTION_ALLIANCE', 'FACTION_HORDE', 'HELP_LABEL', 'ATTACK', 'HEALTH', 'BLUE_GEM', 'RED_GEM', 'OPTIONS', 'MAX_RAID_MEMBERS', 'BATTLEGROUND', 'hooksecurefunc', 'issecurevariable', 'FriendsFrame', 'FriendsTabHeader'}
ignore = {'self', '532'}
max_line_length = false
self = false
